"use client";
import {useState} from "react";
const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000/api/v1";
export default function Home(){
 const [email,setEmail]=useState("admin@example.local"),[password,setPassword]=useState("change-me-before-use"),[token,setToken]=useState(""),[session,setSession]=useState<any>(null),[message,setMessage]=useState("");
 const request=async(path:string, options:RequestInit={})=>{const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Request failed");return d;};
 async function login(e:React.FormEvent){e.preventDefault();try{let d=await request("/auth/login",{method:"POST",body:JSON.stringify({email,password})});setToken(d.access_token);setMessage("เข้าสู่ระบบแล้ว");}catch(e:any){setMessage(e.message)}}
 async function create(){try{let s=await request("/sessions",{method:"POST",body:"{}"});setSession(s);await request(`/sessions/${s.id}/start`,{method:"POST",body:"{}"});setMessage("สร้าง session เรียบร้อย");}catch(e:any){setMessage(e.message)}}
 return <main><header><h1>AI Call Center</h1><span>Configuration-driven intake workspace</span></header>{!token?<form onSubmit={login}><h2>Operator sign in</h2><input aria-label="email" value={email} onChange={e=>setEmail(e.target.value)}/><input aria-label="password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button>Sign in</button></form>:<section className="workspace"><aside><h2>Dynamic form</h2><p>Form values appear here with status, confidence, and transcript provenance.</p><button onClick={create}>Create call session</button>{session&&<pre>{JSON.stringify(session,null,2)}</pre>}</aside><article><h2>Conversation</h2><p>Microphone capture connects only to the authenticated realtime gateway. AI providers are never called from this browser.</p><button onClick={()=>setMessage("Microphone workflow is ready for an active session.")}>Start microphone</button><textarea placeholder="Human correction or notes" /></article></section>}<output role="status">{message}</output></main>
}
