"use client";
import {useEffect, useRef, useState} from "react";
const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000/api/v1";
const WS = process.env.NEXT_PUBLIC_WS_BASE_URL || "ws://localhost:8080";
export default function Home(){
 const [email,setEmail]=useState("admin@example.local"),[password,setPassword]=useState("change-me-before-use"),[token,setToken]=useState(""),[session,setSession]=useState<any>(null),[message,setMessage]=useState(""),[transcript,setTranscript]=useState<string[]>([]),[recording,setRecording]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null), socket=useRef<WebSocket|null>(null), logPanel=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{logPanel.current?.scrollTo({top:logPanel.current.scrollHeight,behavior:"smooth"})},[transcript]);
 const request=async(path:string, options:RequestInit={})=>{const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Request failed");return d;};
 async function login(e:React.FormEvent){e.preventDefault();try{let d=await request("/auth/login",{method:"POST",body:JSON.stringify({email,password})});setToken(d.access_token);setMessage("เข้าสู่ระบบแล้ว");}catch(e:any){setMessage(e.message)}}
 async function create(){try{let s=await request("/sessions",{method:"POST",body:"{}"});let started=await request(`/sessions/${s.id}/start`,{method:"POST",body:"{}"});setSession(started);setTranscript([]);setMessage("สร้างและเริ่ม session แล้ว — กด Start microphone เพื่อเริ่มรับเสียง");}catch(e:any){setMessage(e.message)}}
 async function startMic(){if(!session)return setMessage("กรุณาสร้าง Call session ก่อน");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const ws=new WebSocket(`${WS}/ws?session_id=${session.id}&access_token=${token}`);socket.current=ws;ws.onmessage=e=>{const event=JSON.parse(e.data);if(event.type==="transcript.final"||event.type==="ai.text")setTranscript(old=>[...old,`${event.speaker||"AI"}: ${event.text||""}`]);if(event.type==="error")setMessage(event.message)};ws.onopen=()=>{ws.send(JSON.stringify({type:"audio.start"}));const rec=new MediaRecorder(stream);rec.ondataavailable=async e=>{if(!e.data.size||ws.readyState!==WebSocket.OPEN)return;const bytes=new Uint8Array(await e.data.arrayBuffer());let binary="";bytes.forEach(b=>binary+=String.fromCharCode(b));ws.send(JSON.stringify({type:"audio.chunk",sequence:Date.now(),data:btoa(binary)}));};rec.start(500);recorder.current=rec;setRecording(true);setMessage("กำลังรับเสียง… กด Stop microphone เพื่อจบ turn")};}catch(e:any){setMessage(`ไม่สามารถเปิดไมโครโฟน: ${e.message}`)}}
 function stopMic(){recorder.current?.stop();recorder.current?.stream.getTracks().forEach(t=>t.stop());socket.current?.send(JSON.stringify({type:"audio.stop"}));setRecording(false);setMessage("ส่งเสียงแล้ว — ดู transcript ทางขวา")}
 return <main><header><h1>AI Call Center</h1><span>Configuration-driven intake workspace</span></header>{!token?<form onSubmit={login}><h2>Operator sign in</h2><input aria-label="email" value={email} onChange={e=>setEmail(e.target.value)}/><input aria-label="password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button>Sign in</button></form>:<section className="workspace"><aside><h2>Dynamic form</h2><p>Form values appear here with status, confidence, and transcript provenance.</p><button onClick={create}>Create call session</button>{session&&<pre>{JSON.stringify(session,null,2)}</pre>}</aside><article><h2>Conversation</h2><p>1. Create session  2. Start microphone  3. Speak  4. Stop microphone</p><button onClick={recording?stopMic:startMic}>{recording?"Stop microphone":"Start microphone"}</button><div className="conversation-log" ref={logPanel} aria-live="polite" aria-label="Conversation log">{transcript.length?transcript.map((line,i)=><p key={i} className={line.startsWith("AI:")?"ai-log":"caller-log"}>{line}</p>):<p className="empty-log">Transcript จะปรากฏที่นี่เมื่อเริ่มสนทนา</p>}</div><textarea placeholder="Human correction or notes" /></article></section>}<output role="status">{message}</output></main>
}
