"use client";
import {useEffect, useRef, useState} from "react";
const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000/api/v1";
const WS = process.env.NEXT_PUBLIC_WS_BASE_URL || "ws://localhost:8080";
export default function Home(){
 const [email,setEmail]=useState("admin@example.local"),[password,setPassword]=useState("change-me-before-use"),[token,setToken]=useState(""),[session,setSession]=useState<any>(null),[message,setMessage]=useState(""),[transcript,setTranscript]=useState<string[]>([]),[recording,setRecording]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null), socket=useRef<WebSocket|null>(null), logPanel=useRef<HTMLDivElement|null>(null), analyserTimer=useRef<number|undefined>(), audioContext=useRef<AudioContext|null>(null), heardSpeech=useRef(false), silenceSince=useRef<number|null>(null);
 useEffect(()=>{logPanel.current?.scrollTo({top:logPanel.current.scrollHeight,behavior:"smooth"})},[transcript]);
 const request=async(path:string, options:RequestInit={})=>{const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Request failed");return d;};
 async function login(e:React.FormEvent){e.preventDefault();try{let d=await request("/auth/login",{method:"POST",body:JSON.stringify({email,password})});setToken(d.access_token);setMessage("เข้าสู่ระบบแล้ว");}catch(e:any){setMessage(e.message)}}
 async function create(){try{let s=await request("/sessions",{method:"POST",body:"{}"});let started=await request(`/sessions/${s.id}/start`,{method:"POST",body:"{}"});setSession(started);setTranscript([]);setMessage("สร้างและเริ่ม session แล้ว — กด Start microphone เพื่อเริ่มรับเสียง");}catch(e:any){setMessage(e.message)}}
 async function startMic(){if(!session)return setMessage("กรุณาสร้าง Call session ก่อน");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const ws=new WebSocket(`${WS}/ws?session_id=${session.id}&access_token=${token}`);socket.current=ws;ws.onmessage=e=>{const event=JSON.parse(e.data);if(event.type==="transcript.final"||event.type==="ai.text")setTranscript(old=>[...old,`${event.speaker||"AI"}: ${event.text||""}`]);if(event.type==="error")setMessage(event.message)};ws.onopen=()=>{ws.send(JSON.stringify({type:"audio.start"}));const rec=new MediaRecorder(stream);rec.ondataavailable=async e=>{if(!e.data.size||ws.readyState!==WebSocket.OPEN)return;const bytes=new Uint8Array(await e.data.arrayBuffer());let binary="";bytes.forEach(b=>binary+=String.fromCharCode(b));ws.send(JSON.stringify({type:"audio.chunk",sequence:Date.now(),data:btoa(binary)}));};rec.start(500);recorder.current=rec;const context=new AudioContext();audioContext.current=context;const analyser=context.createAnalyser();analyser.fftSize=512;context.createMediaStreamSource(stream).connect(analyser);const samples=new Uint8Array(analyser.fftSize);analyserTimer.current=window.setInterval(()=>{analyser.getByteTimeDomainData(samples);const volume=samples.reduce((sum,sample)=>sum+Math.abs(sample-128),0)/samples.length/128;const time=Date.now();if(volume>.018){heardSpeech.current=true;silenceSince.current=null;return}if(!heardSpeech.current)return;if(!silenceSince.current){silenceSince.current=time;return}if(time-silenceSince.current>1200&&ws.readyState===WebSocket.OPEN){ws.send(JSON.stringify({type:"audio.stop"}));ws.send(JSON.stringify({type:"audio.start"}));heardSpeech.current=false;silenceSince.current=null;setMessage("ส่ง turn ให้ AI แล้ว — กำลังฟังต่อเนื่อง")}},200);setRecording(true);setMessage("กำลังฟังต่อเนื่อง — ระบบจะส่งข้อความเมื่อคุณเงียบประมาณ 1.2 วินาที")};}catch(e:any){setMessage(`ไม่สามารถเปิดไมโครโฟน: ${e.message}`)}}
 function stopMic(){if(analyserTimer.current)window.clearInterval(analyserTimer.current);audioContext.current?.close();recorder.current?.stop();recorder.current?.stream.getTracks().forEach(t=>t.stop());socket.current?.send(JSON.stringify({type:"audio.stop"}));socket.current?.close();setRecording(false);setMessage("จบการสนทนาแล้ว")}
 return <main><header><h1>AI Call Center</h1><span>Configuration-driven intake workspace</span></header>{!token?<form onSubmit={login}><h2>Operator sign in</h2><input aria-label="email" value={email} onChange={e=>setEmail(e.target.value)}/><input aria-label="password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button>Sign in</button></form>:<section className="workspace"><aside><h2>Dynamic form</h2><p>Form values appear here with status, confidence, and transcript provenance.</p><button onClick={create}>Create call session</button>{session&&<pre>{JSON.stringify(session,null,2)}</pre>}</aside><article><h2>Conversation</h2><p>เริ่มไมโครโฟนหนึ่งครั้ง แล้วพูดได้ต่อเนื่อง ระบบจบแต่ละ turn จากช่วงเงียบอัตโนมัติ</p><button onClick={recording?stopMic:startMic}>{recording?"End call":"Start continuous conversation"}</button><div className="conversation-log" ref={logPanel} aria-live="polite" aria-label="Conversation log">{transcript.length?transcript.map((line,i)=><p key={i} className={line.startsWith("AI:")?"ai-log":"caller-log"}>{line}</p>):<p className="empty-log">Transcript จะปรากฏที่นี่เมื่อเริ่มสนทนา</p>}</div><textarea placeholder="Human correction or notes" /></article></section>}<output role="status">{message}</output></main>
}
